export enum Permission {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  VIEW_TEAM = 'VIEW_TEAM',
  VIEW_REPORT = 'VIEW_REPORT',
  MANAGE_COMPANY = 'MANAGE_COMPANY',
  MANAGE_SHIFT = 'MANAGE_SHIFT',
  ASSIGN_MEMBER = 'ASSIGN_MEMBER',
  VIEW_SCREENSHOTS = 'VIEW_SCREENSHOTS',
  SEND_CHAT = 'SEND_CHAT',
}
